"""Browser Anti-Fingerprint — Harden Firefox for anonymous recon.

Generates a hardened Firefox profile that:
- Disables WebRTC (prevents IP leak even behind proxy/VPN)
- Disables DNS prefetch (prevents DNS leak)
- Disables HSTS tracking
- Blocks WebRTC STUN/TURN candidates
- Spoofs canvas fingerprint
- Disables telemetry

Usage:
    python3 -m core.browser_harden              # Generate profile
    python3 -m core.browser_harden --launch      # Generate + launch Firefox
    python3 -m core.browser_harden --check       # Check current Firefox for leaks
"""

import os
import sys
import json
import subprocess
import platform
from pathlib import Path


# Firefox about:config hardening values
FIREFOX_HARDENING = {
    # === WebRTC IP Leak Prevention ===
    "media.peerconnection.enabled": False,           # Disable WebRTC entirely
    "media.peerconnection.ice.default_address_only": True,  # Only use default interface
    "media.peerconnection.ice.no_host": True,        # Don't expose local IP
    "media.peerconnection.ice.proxy_only_if_behind_proxy": True,
    "media.peerconnection.ice.proxy_only": True,     # Force proxy for ICE

    # === DNS Leak Prevention ===
    "network.dns.disablePrefetch": True,             # No DNS prefetch
    "network.dns.disablePrefetchFromHTTPS": True,    # No HTTPS DNS prefetch
    "network.dns.disableIPv6": True,                 # No IPv6 DNS (can leak)
    "network.predictor.enabled": False,              # No predictive connections
    "network.predictor.enable-prefetch": False,
    "network.prefetch-next": False,                  # No link prefetch

    # === Proxy Enforcement ===
    "network.proxy.socks_remote_dns": True,          # DNS through proxy (SOCKS5)
    "media.peerconnection.default_iceservers": "[]", # No STUN servers

    # === Tracking Prevention ===
    "privacy.trackingprotection.enabled": True,
    "privacy.trackingprotection.socialtracking.enabled": True,
    "privacy.resistFingerprinting": True,            # Resist fingerprinting (Tor-like)
    "privacy.firstparty.isolate": True,              # First-party isolation

    # === Telemetry Disable ===
    "toolkit.telemetry.enabled": False,
    "toolkit.telemetry.unified": False,
    "toolkit.telemetry.archive.enabled": False,
    "datareporting.healthreport.uploadEnabled": False,
    "datareporting.policy.dataSubmissionEnabled": False,
    "browser.ping-centre.telemetry": False,
    "browser.aboutHomeSnippets.updateUrl": "",

    # === Canvas Fingerprint Protection ===
    "privacy.resistFingerprinting": True,            # Spoofs canvas, timezone, etc.

    # === HSTS Tracking Prevention ===
    "security.OCSP.enabled": 0,                      # No OCSP (can leak)
    "network.http.speculative-parallel-limit": 0,    # No speculative connections

    # === WebRTC STUN/TURN Block ===
    "media.peerconnection.turn.disable": True,       # No TURN
    "media.peerconnection.ice.tcp_so_sock_count": 0, # No TCP ICE

    # === Misc Privacy ===
    "dom.battery.enabled": False,                    # No battery API
    "dom.gamepad.enabled": False,                    # No gamepad fingerprint
    "dom.vibrator.enabled": False,                   # No vibration API
    "geo.enabled": False,                            # No geolocation
    "geo.wifi.uri": "",                              # No WiFi geolocation
    "media.navigator.enabled": False,                # No media device enum
    "network.http.sendRefererHeader": 0,             # No referer
    "network.http.referer.XOriginPolicy": 2,        # No cross-origin referer
}


def get_profile_dir() -> Path:
    """Get Firefox profile directory."""
    system = platform.system()
    if system == "Linux":
        return Path.home() / ".mozilla" / "firefox"
    elif system == "Darwin":
        return Path.home() / "Library" / "Application Support" / "Firefox" / "Profiles"
    elif system == "Windows":
        return Path(os.environ.get("APPDATA", "")) / "Mozilla" / "Firefox" / "Profiles"
    return Path.home() / ".firefox-hardened"


def generate_profile(name: str = "verdamt-hardened") -> Path:
    """Generate a hardened Firefox profile.
    
    Returns path to the profile directory.
    """
    base = get_profile_dir()
    profile_dir = base / name
    profile_dir.mkdir(parents=True, exist_ok=True)

    # user.js — applied on every Firefox start
    user_js = profile_dir / "user.js"
    lines = [
        "// verdamt-snipe hardened Firefox profile",
        "// Generated by core/browser_harden.py",
        "// Prevents: WebRTC leak, DNS leak, fingerprinting, telemetry",
        "",
    ]
    for key, value in FIREFOX_HARDENING.items():
        if isinstance(value, bool):
            lines.append(f'user_pref("{key}", {"true" if value else "false"});')
        elif isinstance(value, int):
            lines.append(f'user_pref("{key}", {value});')
        elif isinstance(value, str):
            lines.append(f'user_pref("{key}", "{value}");')

    user_js.write_text("\n".join(lines) + "\n")

    # userChrome.css — UI hardening
    chrome_dir = profile_dir / "chrome"
    chrome_dir.mkdir(exist_ok=True)
    userchrome = chrome_dir / "userChrome.css"
    userchrome.write_text("""\
/* verdamt-snipe hardened Firefox CSS */
/* Disable WebRTC indicator */
#webrtc-indicator { display: none !important; }
/* Hide tracking protection icon (don't reveal we're blocking) */
#tracking-protection-icon-container { display: none !important; }
""")

    print(f"[*] Hardened profile created: {profile_dir}")
    print(f"[*] user.js: {user_js}")
    print(f"[*] Settings applied: {len(FIREFOX_HARDENING)}")
    return profile_dir


def check_firefox_leaks() -> dict:
    """Check current Firefox settings for IP/DNS leak risks."""
    results = {
        "webRTC_leak": True,
        "dns_prefetch": True,
        "telemetry": True,
        "fingerprinting": True,
        "issues": [],
    }

    profile_dir = get_profile_dir()
    if not profile_dir.exists():
        results["issues"].append("Firefox profile directory not found")
        return results

    # Look for prefs.js in profiles
    for prefs_file in profile_dir.rglob("prefs.js"):
        try:
            content = prefs_file.read_text()
            
            # Check WebRTC
            if '"media.peerconnection.enabled",false' in content:
                results["webRTC_leak"] = False
            
            # Check DNS prefetch
            if '"network.dns.disablePrefetch",true' in content:
                results["dns_prefetch"] = False
            
            # Check telemetry
            if '"toolkit.telemetry.enabled",false' in content:
                results["telemetry"] = False
            
            # Check fingerprinting
            if '"privacy.resistFingerprinting",true' in content:
                results["fingerprinting"] = False
                
        except Exception:
            pass

    if results["webRTC_leak"]:
        results["issues"].append("WebRTC enabled — IP can leak even behind proxy")
    if results["dns_prefetch"]:
        results["issues"].append("DNS prefetch enabled — DNS queries can leak")
    if results["telemetry"]:
        results["issues"].append("Telemetry enabled — data sent to Mozilla")
    if results["fingerprinting"]:
        results["issues"].append("Fingerprinting protection disabled")

    if not results["issues"]:
        results["issues"].append("All checks passed — browser is hardened")

    return results


def launch_firefox(profile_name: str = "verdamt-hardened", url: str = None):
    """Launch Firefox with hardened profile."""
    profile_dir = get_profile_dir() / profile_name
    
    if not profile_dir.exists():
        print(f"[!] Profile not found: {profile_dir}")
        print(f"[*] Run: python3 -m core.browser_harden")
        return

    cmd = ["firefox", "-P", profile_name, "--no-remote"]
    if url:
        cmd.append(url)

    print(f"[*] Launching Firefox with profile: {profile_name}")
    print(f"[*] Command: {' '.join(cmd)}")
    
    try:
        subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        print("[*] Firefox launched")
    except FileNotFoundError:
        print("[!] Firefox not found in PATH")


def print_check_results(results: dict):
    """Print leak check results."""
    print("\n=== Firefox Leak Check ===\n")
    
    checks = [
        ("WebRTC IP Leak", results["webRTC_leak"]),
        ("DNS Prefetch Leak", results["dns_prefetch"]),
        ("Telemetry Active", results["telemetry"]),
        ("Fingerprinting Unprotected", results["fingerprinting"]),
    ]
    
    for name, vulnerable in checks:
        status = "VULNERABLE" if vulnerable else "PROTECTED"
        icon = "!!" if vulnerable else "OK"
        print(f"  [{icon}] {name}: {status}")
    
    print()
    for issue in results["issues"]:
        print(f"  -> {issue}")
    print()


if __name__ == "__main__":
    args = sys.argv[1:]
    
    if "--check" in args:
        results = check_firefox_leaks()
        print_check_results(results)
    elif "--launch" in args:
        profile_dir = generate_profile()
        launch_firefox()
    else:
        profile_dir = generate_profile()
        print(f"\n[*] To use this profile:")
        print(f"    firefox -P verdamt-hardened --no-remote")
        print(f"\n[*] Or launch automatically:")
        print(f"    python3 -m core.browser_harden --launch")
        print(f"\n[*] To check existing Firefox:")
        print(f"    python3 -m core.browser_harden --check")
